name: "Check if first release"
description: "Check if this is the first release by querying Factorio MOD Portal API"
author: "sakuro"
inputs:
  mod_name:
    description: "Name of the MOD to check"
    required: true
outputs:
  is_first_release:
    description: "true if this is the first release, false otherwise"
    value: ${{ steps.check.outputs.is_first_release }}
runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      env:
        MOD_NAME: ${{ inputs.mod_name }}
      run: |
        # Check if MOD exists on Factorio MOD Portal
        # Returns 404 if MOD doesn't exist (first release)
        # Returns 200 if MOD exists (subsequent release)
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://mods.factorio.com/api/mods/$MOD_NAME")

        if [ "$HTTP_STATUS" = "404" ]; then
          echo "is_first_release=true" >> $GITHUB_OUTPUT
          echo "MOD not found on portal - this is the first release"
        elif [ "$HTTP_STATUS" = "200" ]; then
          echo "is_first_release=false" >> $GITHUB_OUTPUT
          echo "MOD found on portal - this is a subsequent release"
        else
          echo "❌ Error: Unexpected HTTP status $HTTP_STATUS from Factorio MOD Portal API"
          echo ""
          echo "Expected either:"
          echo "  - 404 (MOD doesn't exist - first release)"
          echo "  - 200 (MOD exists - subsequent release)"
          echo ""
          echo "Please check:"
          echo "1. MOD Portal API availability: https://mods.factorio.com/api/mods/$MOD_NAME"
          echo "2. Network connectivity"
          echo "3. MOD name correctness: $MOD_NAME"
          exit 1
        fi
