name: "Create release pull request"
description: "Create a pull request for release preparation with appropriate checklist"
author: "sakuro"
inputs:
  version:
    description: "Release version (e.g., 1.0.0)"
    required: true
  mod_name:
    description: "Name of the MOD"
    required: true
  is_first_release:
    description: "Whether this is the first release (true/false)"
    required: true
  repository:
    description: "Repository name (owner/repo)"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # Generate PR body based on whether this is the first release
        if [ "${{ inputs.is_first_release }}" = "true" ]; then
          # First release - include full setup checklist
          PR_BODY="$(cat <<'EOF'
        ## Summary

        Prepare for release v${{ inputs.version }}

        **Note**: This is the first release for this Factorio MOD.

        ## Changes

        - Update version in info.json to ${{ inputs.version }}
        - Add changelog.txt section for this release

        ## Quality Checks

        These checks will be performed automatically by CI and validation workflows:

        - Version format validation
        - changelog.txt format validation
        - MOD_PORTAL_API_KEY validation

        ## Release Requirements Checklist

        Before merging this PR, ensure the following requirements are met:

        ### GitHub Repository Settings
        - [ ] **Workflow permissions**: Set to "Read and write permissions"
        - [ ] **Pull request permissions**: Check "Allow GitHub Actions to create and approve pull requests"
        - [ ] Configure at: https://github.com/${{ inputs.repository }}/settings/actions

        ### Factorio MOD Portal Setup
        - [ ] **MOD Portal Account**: Create account at https://mods.factorio.com if not already done
        - [ ] **MOD name availability**: Verify `${{ inputs.mod_name }}` is available or owned by you
        - [ ] **API Key**: Generate API key at https://factorio.com/profile

        ### GitHub Environment Configuration
        - [ ] **Create `release` environment** at: https://github.com/${{ inputs.repository }}/settings/environments
        - [ ] **Add `MOD_PORTAL_API_KEY` secret to release environment**
          - Click on the `release` environment, then "Add secret"
          - This provides better security than repository-level secrets
        - [ ] **Add environment protection rules** (optional but recommended):
          - Required reviewers (optional but recommended)
          - Wait timer (optional)

        ### Repository Settings
        - [ ] **Branch protection**: Consider protecting the main branch
        - [ ] **Auto-delete head branches**: Enable to auto-delete merged release branches
        - [ ] Configure at: https://github.com/${{ inputs.repository }}/settings

        ## Post-Merge Actions

        After merging this PR, the release workflow will automatically:
        - Use the git tag v${{ inputs.version }} (already created on this branch)
        - Build the MOD package from the tagged commit
        - Upload to Factorio MOD Portal
        - Create GitHub release with assets

        EOF
        )"
        else
          # Subsequent release - simplified checklist
          PR_BODY="$(cat <<'EOF'
        ## Summary

        Prepare for release v${{ inputs.version }}

        ## Changes

        - Update version in info.json to ${{ inputs.version }}
        - Add changelog.txt section for this release

        ## Quality Checks

        These checks will be performed automatically by CI and validation workflows:

        - Version format validation
        - changelog.txt format validation
        - MOD_PORTAL_API_KEY validation

        ## Release Requirements Checklist

        Before merging this PR, ensure the following requirements are met:

        - [ ] **changelog.txt**: Verify all notable changes are documented
        - [ ] **Breaking changes**: If any, ensure they are clearly documented in changelog
        - [ ] **Dependencies**: Check if any MOD dependency updates are needed in info.json
        - [ ] **Factorio version**: Verify factorio_version in info.json is correct
        - [ ] **README**: Ensure README.md reflects any new features or changes

        ## Post-Merge Actions

        After merging this PR, the release workflow will automatically:
        - Use the git tag v${{ inputs.version }} (already created on this branch)
        - Build the MOD package from the tagged commit
        - Upload to Factorio MOD Portal
        - Create GitHub release with assets

        EOF
        )"
        fi

        # Create PR with the appropriate body
        gh pr create --title ":bookmark: Release v${{ inputs.version }}" --body "$PR_BODY"
