name: "Upload MOD to Factorio MOD portal"
description: "Upload a MOD to the Factorio MOD portal via API"
author: "sakuro"
inputs:
  mod_name:
    description: "Name of the MOD to upload"
    required: true
  mod_version:
    description: "Version of the MOD to upload"
    required: true
  zip_name:
    description: "Zip archive name of the MOD to be uploaded"
    required: true
  api_key:
    description: "MOD portal API key for upload"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        MOD_NAME: ${{ inputs.mod_name }}
        ZIP_NAME: ${{ inputs.zip_name }}
        MOD_PORTAL_API_KEY: ${{ inputs.api_key }}
      run: |
        INIT_UPLOAD_URL="https://mods.factorio.com/api/v2/mods/releases/init_upload"

        # Get upload URL
        set -- $(curl -s -X POST -H "Authorization: Bearer $MOD_PORTAL_API_KEY" -F "mod=$MOD_NAME" "$INIT_UPLOAD_URL" | jq -r '.upload_url, .error, .message')
        UPLOAD_URL="$1"
        ERROR="$2"
        MESSAGE="$3"

        if [ "$ERROR" != "null" ]; then
          echo "❌ Error initializing upload: $ERROR: $MESSAGE"
          exit 1
        fi

        # Upload the MOD file
        set -- $(curl -s -X POST -F file=@"$ZIP_NAME" "$UPLOAD_URL" | jq -r '.success, .error, .message')
        SUCCESS="$1"
        ERROR="$2"
        MESSAGE="$3"

        if [ "$ERROR" != "null" ]; then
          echo "❌ Error uploading MOD: $ERROR: $MESSAGE"
          exit 1
        fi

        echo "✅ MOD uploaded successfully to Factorio MOD portal"
