name: "Validate version format"
description: "Validate that version follows semantic versioning format (x.y.z)"
author: "sakuro"
inputs:
  version:
    description: "Version to validate (e.g., 1.0.0)"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        if ! echo "$VERSION" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "❌ Error: Version must be in format x.y.z (e.g., 1.0.0)"
          echo ""
          echo "Provided version: $VERSION"
          exit 1
        fi
        echo "✅ Version format is valid: $VERSION"
